use_frameworks!

target 'Gluon_Example' do
  pod 'Gluon', :path => '../'

  target 'Gluon_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.1'
    pod 'Nimble', '~> 7.3.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
