target 'TokamakDemo' do
  platform :ios, '11.0'

  pod 'Tokamak', :path => '..'
  pod 'TokamakUIKit', :path => '..'
end

target 'TokamakDemoMac' do
  platform :macos, '10.14'

  pod 'Tokamak', :path => '..'
  pod 'TokamakAppKit', :path => '..'
end
