def common_pods
  pod 'Tokamak', :path => '..'
  pod 'TokamakDemo', :path => '..'
end


target 'TokamakDemo-iOS' do
  platform :ios, '11.0'

  common_pods
  pod 'Alamofire'
  pod 'TokamakUIKit', :path => '..'
end

target 'TokamakDemo-macOS' do
  platform :macos, '10.14'

  common_pods
  pod 'TokamakAppKit', :path => '..'
end
