disabled_rules:
- trailing_comma
- identifier_name
- void_return
- operator_whitespace
- nesting
- cyclomatic_complexity

line_length:
- 80
- 100
- ignores_comments


function_body_length:
- 50

included:
  - Sources
  - Tests