ALL:
	cd src/TokamakDevTools && ~/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/bin/swift build --triple wasm32-unknown-wasi
	cp src/TokamakDevTools/.build/debug/TokamakDevTools src/main.wasm

rebuild:
	cd src/TokamakDevTools && ~/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/bin/swift build --triple wasm32-unknown-wasi
	cp src/TokamakDevTools/.build/debug/TokamakDevTools build/main.wasm
