#if !canImport(ObjectiveC)
import XCTest

extension ColorTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__ColorTests = [
    ("testHexColors", testHexColors),
  ]
}

extension ReconcilerTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__ReconcilerTests = [
    ("testDoubleUpdate", testDoubleUpdate),
    ("testMount", testMount),
    ("testUnmount", testUnmount),
    ("testUpdate", testUpdate),
  ]
}

public func __allTests() -> [XCTestCaseEntry] {
  [
    testCase(ColorTests.__allTests__ColorTests),
    testCase(ReconcilerTests.__allTests__ReconcilerTests),
  ]
}
#endif
